language: scala
scala:
   - 2.13.0
script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts clean test
jdk:
    - oraclejdk11

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier

