version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka0:
    build: .
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.14
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.14:9092"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka1:
    build: .
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.14
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.14:9092"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    build: .
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.14
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.14:9092"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
